config/routes.rb
PapillonnoceurFirst::Application.routes.draw do

  resources :proposition_covoiturages#, :only => [:create,:update,:destroy]
  resources :demande_covoiturages

  root :to => 'pages#accueil'
  match '/presentation', :to => 'pages#presentation'
  match '/trajet', :to => 'pages#trajet'
  match '/covoiturage', :to => 'pages#covoiturage'
  match '/logement', :to => 'pages#logement'
  match '/liste', :to => 'pages#liste'
  match '/photos', :to => 'pages#photos'

end

app/models/demande_covoiturage.rb
# coding: utf-8
class DemandeCovoiturage < ActiveRecord::Base
	attr_accessible :depart, :places, :name, :email, :telephone

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :depart, 	:presence => true,
						:length => { :maximum => 30 }

	validates :places,	:presence => true,
						:numericality => { 	:only_integer => true,
											:greater_than => 1,
											:lower_than => 7}

	validates :name, 	:presence => true,
						:length => { :maximum => 30 }

	validates :email, 	:presence => true,
						:format => { :with => email_regex },
						:uniqueness => { :case_sensitive => false },
						:unless => Proc.new {|obj| obj.email.blank? && !obj.telephone.blank?}

	validates :telephone, 	:presence => true,
							:length => { :in => 9..15 },
							:unless => Proc.new {|obj| obj.telephone.blank? && !obj.email.blank?}
end

app/models/proposition_covoiturage.rb
# coding: utf-8
class PropositionCovoiturage < ActiveRecord::Base
	attr_accessible :depart, :places, :name, :email, :telephone

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :depart, 	:presence => true,
						:length => { :maximum => 30 }

	validates :places,	:presence => true,
						:numericality => { 	:only_integer => true,
											:greater_than => 1,
											:lower_than => 7}

	validates :name, 	:presence => true,
						:length => { :maximum => 30 }

	validates :email, 	:presence => true,
						:format => { :with => email_regex },
						:uniqueness => { :case_sensitive => false },
						:unless => Proc.new {|obj| obj.email.blank? && !obj.telephone.blank?}

	validates :telephone, 	:presence => true,
							:length => { :in => 9..15 },
							:unless => Proc.new {|obj| obj.telephone.blank? && !obj.email.blank?}

end

app/controllers/demande_covoiturages_controller.rb
# coding: utf-8
class DemandeCovoituragesController < ApplicationController
  def create
  	@demande_covoiturages = DemandeCovoiturage.all
  	@demande_covoiturage = DemandeCovoiturage.new(params[:demande_covoiturage])
  	if @demande_covoiturage.save
      respond_to do |format|
        format.html { redirect_to covoiturage_path, :flash => { :success => "Demande prise en compte!"} }
        format.js
      end
    else
      render 'pages/covoiturage'
    end
  end

  def destroy
  	DemandeCovoiturage.find(params[:id]).destroy
    @demande_covoiturages = DemandeCovoiturage.all
    respond_to do |format|
      format.html { redirect_to covoiturage_path, :flash => { :success => "Demande supprimée!" } }
      format.js
    end
  end

end

app/controllers/pages_controller.rb
# coding: utf-8

class PagesController < ApplicationController
  def accueil
    @title = "Infos pratiques"
  end

  def presentation
    @title = "Présentation"
  end

  def trajet
    @title = "Trajet"
  end

  def covoiturage
    @title = "Covoiturage"
    @proposition_covoiturages = PropositionCovoiturage.all
    @proposition_covoiturage = PropositionCovoiturage.new
    @demande_covoiturages = DemandeCovoiturage.all
    @demande_covoiturage = DemandeCovoiturage.new
  end

  def logement
    @title = "Logement"
  end

  def liste
    @title = "Liste"
  end

end

app/controllers/proposition_covoiturages_controller.rb
# coding: utf-8
class PropositionCovoituragesController < ApplicationController
  def create
    @proposition_covoiturages = PropositionCovoiturage.all
  	@proposition_covoiturage = PropositionCovoiturage.new(params[:proposition_covoiturage])
  	if @proposition_covoiturage.save
      respond_to do |format|
        format.html { redirect_to covoiturage_path, :flash => { :success => "Proposition prise en compte!"} }
        format.js
      end
    else
      render 'pages/covoiturage'
    end
  end

  def update
  	
  end

  def destroy
  	PropositionCovoiturage.find(params[:id]).destroy
    @proposition_covoiturages = PropositionCovoiturage.all
    respond_to do |format|
      format.html { redirect_to covoiturage_path, :flash => { :success => "Proposition supprimée!" } }
      format.js
    end
  end

end

app/helpers/application_helper.rb
# coding: utf-8

module ApplicationHelper
	def title
		base_title = "Mariage de Marie-Caroline et Charles-Hubert"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/demande_covoiturages_helper.rb
module DemandeCovoituragesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/proposition_covoiturages_helper.rb
module PropositionCovoituragesHelper
end

app/views/demande_covoiturages/_demande_covoiturage.html.erb
	<div class="proposition">
		
		<div class="proposition-important">
			<div class="depart">
				<h4><span class="darker">Départ:</span> <%= demande_covoiturage.depart %></h4> 
			</div>
		</div>
		<div class="proposition-contact">
			<div class="email">
				<h4><%= mail_to demande_covoiturage.email, "Envoyer un email" %></h4>
			</div>
			
			<div class="telephone">
				<h4><%= demande_covoiturage.telephone %></h4>
			</div>
		</div>
		<div class="proposition-annexe">
			<span class="name">
				Demandé par <strong><%= demande_covoiturage.name %></strong>
			</span>
			<span class="supprimer">
				<%= link_to "Supprimer", demande_covoiturage, :method => :delete, :remote => true, :confirm => "Etes-vous sûr(e) ?", :title => "Supprimer la demande" %>
			</span>
		</div>
	</div>

app/views/demande_covoiturages/create.js.erb
/* render the demand */
$("#demandes").append('<%= escape_javascript(render(@demande_covoiturage)) %>');
//reset form
//$("#new_demande_covoiturage")[0].reset();
//hide form
$("#new_demande_covoiturage").hide();
//show demander button
$("#demander-button").show();

app/views/demande_covoiturages/destroy.js.erb
$("#demandes").html("<%= escape_javascript(render(@demande_covoiturages)) %>");

app/views/layouts/_header.html.erb
<header>
	<div class="row">
		<div class="span11">
			<a href="<%= root_path %>"><h1><span class="elle">Marie-Caroline</span> <span class="et">&amp;</span> <span class="lui">Charles-Hubert</span></h1>
		</div>
	</div>
	<div class="row">
		<div class="span9">	
			<nav>
				<ul class="">
					<li><%= link_to "Trajet", trajet_path %></li>
					<li><%= link_to "Covoiturage", covoiturage_path %></li>
					<li><%= link_to "Logement", logement_path %></li>
					<li><%= link_to "Liste", liste_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= title %></title>
  <meta name="description" content="">
  <meta name="author" content="">

  <meta name="viewport" content="width=device-width,initial-scale=1">


  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>

  <%= javascript_include_tag "modernizr-2.0.6.min.js" %>
</head>

<body>
  
  <div class="container">

		<%= render 'layouts/header' %>
    
      <% flash.each do |key, value| %>
        <div class="alert-message <%= key %> fade in" data-alert="alert">
          <a class="close" href="#">×</a>  
          <%= value %>
        </div>
      <% end %>

    	<%= yield %>

      <footer>
        <p>Site réalisé par <a href="http://lancement.papillonnoceur.com">papillonnoceur.com</a> - ©2011 Papillon Noceur - <a href="http://mapicons.nicolasmollet.com">Maps Icons Collection</a> </p>
      </footer>
	</div>
  

  <%= javascript_include_tag "application" %>


  <script>
    var _gaq=[['_setAccount','UA-26913167-1'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->

</body>
</html>

app/views/pages/accueil.html.erb
<div class="watup row">
<div id="mess" class="row">
		<div class="span7 offset1 info-mariage horaires">
			<h2>Messe Samedi 14 avril à 14:30</h2>
			<a href="<%= trajet_path %>"><h3>à l'Eglise Saint-Martin d'Argentan</h3></a>
		</div>
	</div>
	<div id="reception" class="row">
		<div class="span4 offset1 info-mariage horaires">
			<h2>Réception</h2>
			<h3>au Château de Canon</h3>
		</div>
	</div>
	<div id="brunch" class="row">
		<div class="span6 offset9 info-mariage horaires">
			<h2>Brunch le dimanche</h2>
			<h3>3, rue de l'Ormeau - 14700 Falaise</h3>
		</div>
	</div>
</div>
	

app/views/pages/covoiturage.html.erb
<div class="row">
	<div class="span5 covoiturage">
		<div class="page-header">
			<h2>Propositions</h2>
		</div>
		<div id="propositions">
			<%= render @proposition_covoiturages %>
		</div>
		<div id="proposer-form">
			<%= render 'shared/form_proposition' %>
		</div>
		<div class="buttons">
			<button id="proposer-button" class="btn large primary">Proposer</button>
		</div>
	</div>
	<div class="span5 offset6 covoiturage">
		<div class="page-header">
			<h2>Demandes</h2>
		</div>
		<div id="demandes">
			<%= render @demande_covoiturages %>
		</div>
		<div id="demander-form">
			<%= render 'shared/form_demande' %>
		</div>
		<div class="buttons">
			<button id="demander-button" class="btn large primary">Demander</button>
		</div>
	</div>
</div>

app/views/pages/liste.html.erb
<div class="liste">
	<div class="page-header">
				<h2>Liste</h2>
			</div>
	<div class="row">
		<div class="span16">
            <p>Vous pouvez trouver notre liste sur 
                <a href="http://mc-ch.lily-liste.com/">www.lilyliste.fr</a> (01.44.88.57.78) et <a href=" http://mc-et-ch.ameliste.fr">www.ameliste.fr</a> (09.79.94.50.01) !</p>
		</div>
	</div>
</div>

app/views/pages/logement.html.erb
<script type="text/javascript"
    src="http://maps.googleapis.com/maps/api/js?sensor=false&language=fr">
</script>
<div class="logement">
	<div class="page-header">
		<h2>Logement</h2>
	</div>
	<div class="row">
		<div class="span16">
			<h3>Cliquez sur les marqueurs pour obtenir plus d'informations!</h3>
		</div>
	</div>
	<div class="row">
		<div id="map_logement" class="span10" style="margin-top:5px;"></div>
	</div>
</div>

app/views/pages/presentation.html.erb
<div class="row">
	<div class="span7 presentation">
		<div class="page-header">
			<h2>Marie-Caroline</h2>
		</div>
		<div class="photo">
			<%= image_tag "steph-profil-reduced.jpg" %>
		</div>
		<div class="portrait-chinois">
			<p><strong><em>Si c’était un(e):</em></strong></p>
<p>
</p>
		</div>
	</div>
	<div class="span7 offset1 presentation">
		<div class="page-header">
			<h2>Charles-Hubert</h2>
		</div>
		<div class="photo">
			<%= image_tag "renaud-profil-reduced.jpg" %>
		</div>
		<div class="portrait-chinois">
			<p><strong><em>Si c’était un(e):</em></strong></p>
<p>

</p>
		</div>
	</div>
</div>

app/views/pages/trajet.html.erb
<script type="text/javascript"
    src="http://maps.googleapis.com/maps/api/js?sensor=false&language=fr">
</script>
<div class="trajet">
	<div class="page-header">
		<h2>Trajet</h2>
	</div>
	<div class="row">
		<div class="span16">
			<form id="form-trajet" class="form-stacked">
				<div class="clearfix">
					<label for="start" style="width:200px;"><b>Entrez votre adresse de départ:</b></label>
					<div class="input"style="float:left;" >
						<input type="text" id="start" name="start" placeholder="Adresse" class="span5">
						<input type="submit" id="request-itinerary" class="btn primary" value="Afficher mon itinéraire">
						<button id="print-itinerary" class="btn success">Imprimer les instructions</button>
					</div>
					
				</div>
			</form>
		</div>
	</div>
	<div class="row">
		<div id="map_trajet" class="span10"></div>
		<div id="directionsPanel" class="span4"></div>
	</div>
</div>

app/views/proposition_covoiturages/_proposition_covoiturage.html.erb
	<div class="proposition">
		
		<div class="proposition-important">
			<div class="depart">
				<h4><span class="darker">Départ:</span> <%= proposition_covoiturage.depart %></h4> 
			</div>
			<div class="places">
				<h4><span class="darker"></span> <%= pluralize(proposition_covoiturage.places, 'place') %></h4>
			</div>
		</div>
		<div class="proposition-contact">
			<div class="email">
				<h4><%= mail_to proposition_covoiturage.email, "Envoyer un email" %></h4>
			</div>
			
			<div class="telephone">
				<h4><%= proposition_covoiturage.telephone %></h4>
			</div>
		</div>
		<div class="proposition-annexe">
			<span class="name">
				Proposé par <strong><%= proposition_covoiturage.name %></strong>
			</span>
			<span class="supprimer">
				<%= link_to "Supprimer", proposition_covoiturage, :method => :delete, :remote => true, :confirm => "Etes-vous sûr(e) ?", :title => "Supprimer la proposition" %>
			</span>
		</div>
	</div>

app/views/proposition_covoiturages/create.js.erb
/* render the proposition */
$("#propositions").append('<%= escape_javascript(render(@proposition_covoiturage)) %>');
//reset form
//$("#new_proposition_covoiturage")[0].reset();
//hide form
$("#new_proposition_covoiturage").hide();
//show proposer button
$("#proposer-button").show();

app/views/proposition_covoiturages/destroy.js.erb
$("#propositions").html("<%= escape_javascript(render(@proposition_covoiturages)) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        Il y a des erreurs:</h2>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= t msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_demande.html.erb
<%= form_for @demande_covoiturage, :remote => true, :validate => true do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="clearfix">
    <%= f.label :depart, "Ville de départ" %>
    <div class="input">
      <%= f.text_field :depart, :class => "span3" %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :name, "Nom" %>
    <div class="input">
      <%= f.text_field :name, :class => "span3"  %>
    </div>
 </div>
 <div class="clearfix">
    <%= f.label :places %>
    <div class="input">
      <%= f.number_field :places, :class => "span1"  %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :email %>
    <div class="input">
      <%= f.email_field :email, :class => "span3"  %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :telephone, "Téléphone" %>
    <div class="input">
      <%= f.telephone_field :telephone, :class => "span3"  %>
    </div>
  </div>
  <div class="buttons">
    <%= f.submit "Poster", :class => "btn primary" %>
    <button id="annuler-demander-button" class="btn">Annuler</button>
  </div>
<% end %>

app/views/shared/_form_proposition.html.erb
<%= form_for @proposition_covoiturage, :remote => true, :validate => true do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="clearfix">
    <%= f.label :depart, "Ville de départ" %>
    <div class="input">
      <%= f.text_field :depart, :class => "span3" %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :places %>
    <div class="input">
      <%= f.number_field :places, :class => "span1"  %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :name, "Nom" %>
    <div class="input">
      <%= f.text_field :name, :class => "span3"  %>
    </div>
 </div>
  <div class="clearfix">
    <%= f.label :email %>
    <div class="input">
      <%= f.email_field :email, :class => "span3"  %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :telephone, "Téléphone" %>
    <div class="input">
      <%= f.telephone_field :telephone, :class => "span3"  %>
    </div>
  </div>
  <div class="buttons">
    <%= f.submit "Poster", :class => "btn primary" %>
    <button id="annuler-proposer-button" class="btn">Annuler</button>
  </div>
<% end %>